/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SCOPE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_DISCRIMINATOR = new Uint8Array([
  175, 175, 109, 31, 13, 152, 155, 237,
]);

export function getInitializeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INITIALIZE_DISCRIMINATOR);
}

export type InitializeInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountConfiguration extends string | AccountMeta<string> = string,
  TAccountTokenMetadatas extends string | AccountMeta<string> = string,
  TAccountOracleTwaps extends string | AccountMeta<string> = string,
  TAccountOraclePrices extends string | AccountMeta<string> = string,
  TAccountOracleMappings extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountConfiguration extends string
        ? WritableAccount<TAccountConfiguration>
        : TAccountConfiguration,
      TAccountTokenMetadatas extends string
        ? WritableAccount<TAccountTokenMetadatas>
        : TAccountTokenMetadatas,
      TAccountOracleTwaps extends string
        ? WritableAccount<TAccountOracleTwaps>
        : TAccountOracleTwaps,
      TAccountOraclePrices extends string
        ? WritableAccount<TAccountOraclePrices>
        : TAccountOraclePrices,
      TAccountOracleMappings extends string
        ? WritableAccount<TAccountOracleMappings>
        : TAccountOracleMappings,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeInstructionData = {
  discriminator: ReadonlyUint8Array;
  feedName: string;
};

export type InitializeInstructionDataArgs = { feedName: string };

export function getInitializeInstructionDataEncoder(): Encoder<InitializeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["feedName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_DISCRIMINATOR }),
  );
}

export function getInitializeInstructionDataDecoder(): Decoder<InitializeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["feedName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getInitializeInstructionDataCodec(): Codec<
  InitializeInstructionDataArgs,
  InitializeInstructionData
> {
  return combineCodec(
    getInitializeInstructionDataEncoder(),
    getInitializeInstructionDataDecoder(),
  );
}

export type InitializeInput<
  TAccountAdmin extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountConfiguration extends string = string,
  TAccountTokenMetadatas extends string = string,
  TAccountOracleTwaps extends string = string,
  TAccountOraclePrices extends string = string,
  TAccountOracleMappings extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  systemProgram?: Address<TAccountSystemProgram>;
  configuration: Address<TAccountConfiguration>;
  tokenMetadatas: Address<TAccountTokenMetadatas>;
  oracleTwaps: Address<TAccountOracleTwaps>;
  oraclePrices: Address<TAccountOraclePrices>;
  oracleMappings: Address<TAccountOracleMappings>;
  feedName: InitializeInstructionDataArgs["feedName"];
};

export function getInitializeInstruction<
  TAccountAdmin extends string,
  TAccountSystemProgram extends string,
  TAccountConfiguration extends string,
  TAccountTokenMetadatas extends string,
  TAccountOracleTwaps extends string,
  TAccountOraclePrices extends string,
  TAccountOracleMappings extends string,
  TProgramAddress extends Address = typeof SCOPE_PROGRAM_ADDRESS,
>(
  input: InitializeInput<
    TAccountAdmin,
    TAccountSystemProgram,
    TAccountConfiguration,
    TAccountTokenMetadatas,
    TAccountOracleTwaps,
    TAccountOraclePrices,
    TAccountOracleMappings
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountSystemProgram,
  TAccountConfiguration,
  TAccountTokenMetadatas,
  TAccountOracleTwaps,
  TAccountOraclePrices,
  TAccountOracleMappings
> {
  // Program address.
  const programAddress = config?.programAddress ?? SCOPE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    configuration: { value: input.configuration ?? null, isWritable: true },
    tokenMetadatas: { value: input.tokenMetadatas ?? null, isWritable: true },
    oracleTwaps: { value: input.oracleTwaps ?? null, isWritable: true },
    oraclePrices: { value: input.oraclePrices ?? null, isWritable: true },
    oracleMappings: { value: input.oracleMappings ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.configuration),
      getAccountMeta(accounts.tokenMetadatas),
      getAccountMeta(accounts.oracleTwaps),
      getAccountMeta(accounts.oraclePrices),
      getAccountMeta(accounts.oracleMappings),
    ],
    data: getInitializeInstructionDataEncoder().encode(
      args as InitializeInstructionDataArgs,
    ),
    programAddress,
  } as InitializeInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountSystemProgram,
    TAccountConfiguration,
    TAccountTokenMetadatas,
    TAccountOracleTwaps,
    TAccountOraclePrices,
    TAccountOracleMappings
  >);
}

export type ParsedInitializeInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    systemProgram: TAccountMetas[1];
    configuration: TAccountMetas[2];
    tokenMetadatas: TAccountMetas[3];
    oracleTwaps: TAccountMetas[4];
    oraclePrices: TAccountMetas[5];
    oracleMappings: TAccountMetas[6];
  };
  data: InitializeInstructionData;
};

export function parseInitializeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      systemProgram: getNextAccount(),
      configuration: getNextAccount(),
      tokenMetadatas: getNextAccount(),
      oracleTwaps: getNextAccount(),
      oraclePrices: getNextAccount(),
      oracleMappings: getNextAccount(),
    },
    data: getInitializeInstructionDataDecoder().decode(instruction.data),
  };
}
