/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SCOPE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const RESUME_CHAINLINKX_PRICE_DISCRIMINATOR = new Uint8Array([
  136, 48, 103, 146, 227, 97, 87, 108,
]);

export function getResumeChainlinkxPriceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RESUME_CHAINLINKX_PRICE_DISCRIMINATOR,
  );
}

export type ResumeChainlinkxPriceInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfiguration extends string | AccountMeta<string> = string,
  TAccountOraclePrices extends string | AccountMeta<string> = string,
  TAccountOracleMappings extends string | AccountMeta<string> = string,
  TAccountTokensMetadata extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfiguration extends string
        ? ReadonlyAccount<TAccountConfiguration>
        : TAccountConfiguration,
      TAccountOraclePrices extends string
        ? WritableAccount<TAccountOraclePrices>
        : TAccountOraclePrices,
      TAccountOracleMappings extends string
        ? ReadonlyAccount<TAccountOracleMappings>
        : TAccountOracleMappings,
      TAccountTokensMetadata extends string
        ? ReadonlyAccount<TAccountTokensMetadata>
        : TAccountTokensMetadata,
      ...TRemainingAccounts,
    ]
  >;

export type ResumeChainlinkxPriceInstructionData = {
  discriminator: ReadonlyUint8Array;
  token: number;
  feedName: string;
};

export type ResumeChainlinkxPriceInstructionDataArgs = {
  token: number;
  feedName: string;
};

export function getResumeChainlinkxPriceInstructionDataEncoder(): Encoder<ResumeChainlinkxPriceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["token", getU16Encoder()],
      ["feedName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: RESUME_CHAINLINKX_PRICE_DISCRIMINATOR,
    }),
  );
}

export function getResumeChainlinkxPriceInstructionDataDecoder(): Decoder<ResumeChainlinkxPriceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["token", getU16Decoder()],
    ["feedName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getResumeChainlinkxPriceInstructionDataCodec(): Codec<
  ResumeChainlinkxPriceInstructionDataArgs,
  ResumeChainlinkxPriceInstructionData
> {
  return combineCodec(
    getResumeChainlinkxPriceInstructionDataEncoder(),
    getResumeChainlinkxPriceInstructionDataDecoder(),
  );
}

export type ResumeChainlinkxPriceInput<
  TAccountAuthority extends string = string,
  TAccountConfiguration extends string = string,
  TAccountOraclePrices extends string = string,
  TAccountOracleMappings extends string = string,
  TAccountTokensMetadata extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  configuration: Address<TAccountConfiguration>;
  oraclePrices: Address<TAccountOraclePrices>;
  oracleMappings: Address<TAccountOracleMappings>;
  tokensMetadata: Address<TAccountTokensMetadata>;
  token: ResumeChainlinkxPriceInstructionDataArgs["token"];
  feedName: ResumeChainlinkxPriceInstructionDataArgs["feedName"];
};

export function getResumeChainlinkxPriceInstruction<
  TAccountAuthority extends string,
  TAccountConfiguration extends string,
  TAccountOraclePrices extends string,
  TAccountOracleMappings extends string,
  TAccountTokensMetadata extends string,
  TProgramAddress extends Address = typeof SCOPE_PROGRAM_ADDRESS,
>(
  input: ResumeChainlinkxPriceInput<
    TAccountAuthority,
    TAccountConfiguration,
    TAccountOraclePrices,
    TAccountOracleMappings,
    TAccountTokensMetadata
  >,
  config?: { programAddress?: TProgramAddress },
): ResumeChainlinkxPriceInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfiguration,
  TAccountOraclePrices,
  TAccountOracleMappings,
  TAccountTokensMetadata
> {
  // Program address.
  const programAddress = config?.programAddress ?? SCOPE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    configuration: { value: input.configuration ?? null, isWritable: false },
    oraclePrices: { value: input.oraclePrices ?? null, isWritable: true },
    oracleMappings: { value: input.oracleMappings ?? null, isWritable: false },
    tokensMetadata: { value: input.tokensMetadata ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.configuration),
      getAccountMeta(accounts.oraclePrices),
      getAccountMeta(accounts.oracleMappings),
      getAccountMeta(accounts.tokensMetadata),
    ],
    data: getResumeChainlinkxPriceInstructionDataEncoder().encode(
      args as ResumeChainlinkxPriceInstructionDataArgs,
    ),
    programAddress,
  } as ResumeChainlinkxPriceInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfiguration,
    TAccountOraclePrices,
    TAccountOracleMappings,
    TAccountTokensMetadata
  >);
}

export type ParsedResumeChainlinkxPriceInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    configuration: TAccountMetas[1];
    oraclePrices: TAccountMetas[2];
    oracleMappings: TAccountMetas[3];
    tokensMetadata: TAccountMetas[4];
  };
  data: ResumeChainlinkxPriceInstructionData;
};

export function parseResumeChainlinkxPriceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedResumeChainlinkxPriceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      configuration: getNextAccount(),
      oraclePrices: getNextAccount(),
      oracleMappings: getNextAccount(),
      tokensMetadata: getNextAccount(),
    },
    data: getResumeChainlinkxPriceInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
