/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SCOPE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_EMERGENCY_COUNCIL_DISCRIMINATOR = new Uint8Array([
  182, 76, 39, 172, 127, 44, 38, 203,
]);

export function getSetEmergencyCouncilDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_EMERGENCY_COUNCIL_DISCRIMINATOR,
  );
}

export type SetEmergencyCouncilInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfiguration extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfiguration extends string
        ? WritableAccount<TAccountConfiguration>
        : TAccountConfiguration,
      ...TRemainingAccounts,
    ]
  >;

export type SetEmergencyCouncilInstructionData = {
  discriminator: ReadonlyUint8Array;
  newEmergencyCouncil: Address;
  feedName: string;
};

export type SetEmergencyCouncilInstructionDataArgs = {
  newEmergencyCouncil: Address;
  feedName: string;
};

export function getSetEmergencyCouncilInstructionDataEncoder(): Encoder<SetEmergencyCouncilInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["newEmergencyCouncil", getAddressEncoder()],
      ["feedName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_EMERGENCY_COUNCIL_DISCRIMINATOR,
    }),
  );
}

export function getSetEmergencyCouncilInstructionDataDecoder(): Decoder<SetEmergencyCouncilInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["newEmergencyCouncil", getAddressDecoder()],
    ["feedName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getSetEmergencyCouncilInstructionDataCodec(): Codec<
  SetEmergencyCouncilInstructionDataArgs,
  SetEmergencyCouncilInstructionData
> {
  return combineCodec(
    getSetEmergencyCouncilInstructionDataEncoder(),
    getSetEmergencyCouncilInstructionDataDecoder(),
  );
}

export type SetEmergencyCouncilInput<
  TAccountAdmin extends string = string,
  TAccountConfiguration extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  configuration: Address<TAccountConfiguration>;
  newEmergencyCouncil: SetEmergencyCouncilInstructionDataArgs["newEmergencyCouncil"];
  feedName: SetEmergencyCouncilInstructionDataArgs["feedName"];
};

export function getSetEmergencyCouncilInstruction<
  TAccountAdmin extends string,
  TAccountConfiguration extends string,
  TProgramAddress extends Address = typeof SCOPE_PROGRAM_ADDRESS,
>(
  input: SetEmergencyCouncilInput<TAccountAdmin, TAccountConfiguration>,
  config?: { programAddress?: TProgramAddress },
): SetEmergencyCouncilInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfiguration
> {
  // Program address.
  const programAddress = config?.programAddress ?? SCOPE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    configuration: { value: input.configuration ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.configuration),
    ],
    data: getSetEmergencyCouncilInstructionDataEncoder().encode(
      args as SetEmergencyCouncilInstructionDataArgs,
    ),
    programAddress,
  } as SetEmergencyCouncilInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfiguration
  >);
}

export type ParsedSetEmergencyCouncilInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    configuration: TAccountMetas[1];
  };
  data: SetEmergencyCouncilInstructionData;
};

export function parseSetEmergencyCouncilInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetEmergencyCouncilInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), configuration: getNextAccount() },
    data: getSetEmergencyCouncilInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
