/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SCOPE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UPDATE_MAPPING_DISCRIMINATOR = new Uint8Array([
  56, 102, 90, 236, 243, 21, 185, 105,
]);

export function getUpdateMappingDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_MAPPING_DISCRIMINATOR,
  );
}

export type UpdateMappingInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfiguration extends string | AccountMeta<string> = string,
  TAccountOracleMappings extends string | AccountMeta<string> = string,
  TAccountPriceInfo extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfiguration extends string
        ? ReadonlyAccount<TAccountConfiguration>
        : TAccountConfiguration,
      TAccountOracleMappings extends string
        ? WritableAccount<TAccountOracleMappings>
        : TAccountOracleMappings,
      TAccountPriceInfo extends string
        ? ReadonlyAccount<TAccountPriceInfo>
        : TAccountPriceInfo,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateMappingInstructionData = {
  discriminator: ReadonlyUint8Array;
  token: number;
  priceType: number;
  twapEnabled: boolean;
  twapSource: number;
  refPriceIndex: number;
  feedName: string;
  genericData: ReadonlyUint8Array;
};

export type UpdateMappingInstructionDataArgs = {
  token: number;
  priceType: number;
  twapEnabled: boolean;
  twapSource: number;
  refPriceIndex: number;
  feedName: string;
  genericData: ReadonlyUint8Array;
};

export function getUpdateMappingInstructionDataEncoder(): Encoder<UpdateMappingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["token", getU16Encoder()],
      ["priceType", getU8Encoder()],
      ["twapEnabled", getBooleanEncoder()],
      ["twapSource", getU16Encoder()],
      ["refPriceIndex", getU16Encoder()],
      ["feedName", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["genericData", fixEncoderSize(getBytesEncoder(), 20)],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_MAPPING_DISCRIMINATOR }),
  );
}

export function getUpdateMappingInstructionDataDecoder(): Decoder<UpdateMappingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["token", getU16Decoder()],
    ["priceType", getU8Decoder()],
    ["twapEnabled", getBooleanDecoder()],
    ["twapSource", getU16Decoder()],
    ["refPriceIndex", getU16Decoder()],
    ["feedName", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["genericData", fixDecoderSize(getBytesDecoder(), 20)],
  ]);
}

export function getUpdateMappingInstructionDataCodec(): Codec<
  UpdateMappingInstructionDataArgs,
  UpdateMappingInstructionData
> {
  return combineCodec(
    getUpdateMappingInstructionDataEncoder(),
    getUpdateMappingInstructionDataDecoder(),
  );
}

export type UpdateMappingInput<
  TAccountAdmin extends string = string,
  TAccountConfiguration extends string = string,
  TAccountOracleMappings extends string = string,
  TAccountPriceInfo extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  configuration: Address<TAccountConfiguration>;
  oracleMappings: Address<TAccountOracleMappings>;
  priceInfo?: Address<TAccountPriceInfo>;
  token: UpdateMappingInstructionDataArgs["token"];
  priceType: UpdateMappingInstructionDataArgs["priceType"];
  twapEnabled: UpdateMappingInstructionDataArgs["twapEnabled"];
  twapSource: UpdateMappingInstructionDataArgs["twapSource"];
  refPriceIndex: UpdateMappingInstructionDataArgs["refPriceIndex"];
  feedName: UpdateMappingInstructionDataArgs["feedName"];
  genericData: UpdateMappingInstructionDataArgs["genericData"];
};

export function getUpdateMappingInstruction<
  TAccountAdmin extends string,
  TAccountConfiguration extends string,
  TAccountOracleMappings extends string,
  TAccountPriceInfo extends string,
  TProgramAddress extends Address = typeof SCOPE_PROGRAM_ADDRESS,
>(
  input: UpdateMappingInput<
    TAccountAdmin,
    TAccountConfiguration,
    TAccountOracleMappings,
    TAccountPriceInfo
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateMappingInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfiguration,
  TAccountOracleMappings,
  TAccountPriceInfo
> {
  // Program address.
  const programAddress = config?.programAddress ?? SCOPE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    configuration: { value: input.configuration ?? null, isWritable: false },
    oracleMappings: { value: input.oracleMappings ?? null, isWritable: true },
    priceInfo: { value: input.priceInfo ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.configuration),
      getAccountMeta(accounts.oracleMappings),
      getAccountMeta(accounts.priceInfo),
    ],
    data: getUpdateMappingInstructionDataEncoder().encode(
      args as UpdateMappingInstructionDataArgs,
    ),
    programAddress,
  } as UpdateMappingInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfiguration,
    TAccountOracleMappings,
    TAccountPriceInfo
  >);
}

export type ParsedUpdateMappingInstruction<
  TProgram extends string = typeof SCOPE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    configuration: TAccountMetas[1];
    oracleMappings: TAccountMetas[2];
    priceInfo?: TAccountMetas[3] | undefined;
  };
  data: UpdateMappingInstructionData;
};

export function parseUpdateMappingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateMappingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === SCOPE_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      configuration: getNextAccount(),
      oracleMappings: getNextAccount(),
      priceInfo: getNextOptionalAccount(),
    },
    data: getUpdateMappingInstructionDataDecoder().decode(instruction.data),
  };
}
