/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI32Decoder,
  getI32Encoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TEST_ORACLE_DISCRIMINATOR = new Uint8Array([
  198, 49, 63, 134, 232, 251, 168, 28,
]);

export function getTestOracleDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(TEST_ORACLE_DISCRIMINATOR);
}

export type TestOracle = {
  discriminator: ReadonlyUint8Array;
  price: bigint;
  expo: number;
  conf: bigint;
  publishTime: bigint;
};

export type TestOracleArgs = {
  price: number | bigint;
  expo: number;
  conf: number | bigint;
  publishTime: number | bigint;
};

/** Gets the encoder for {@link TestOracleArgs} account data. */
export function getTestOracleEncoder(): FixedSizeEncoder<TestOracleArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["price", getU64Encoder()],
      ["expo", getI32Encoder()],
      ["conf", getU64Encoder()],
      ["publishTime", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TEST_ORACLE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link TestOracle} account data. */
export function getTestOracleDecoder(): FixedSizeDecoder<TestOracle> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["price", getU64Decoder()],
    ["expo", getI32Decoder()],
    ["conf", getU64Decoder()],
    ["publishTime", getI64Decoder()],
  ]);
}

/** Gets the codec for {@link TestOracle} account data. */
export function getTestOracleCodec(): FixedSizeCodec<
  TestOracleArgs,
  TestOracle
> {
  return combineCodec(getTestOracleEncoder(), getTestOracleDecoder());
}

export function decodeTestOracle<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<TestOracle, TAddress>;
export function decodeTestOracle<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<TestOracle, TAddress>;
export function decodeTestOracle<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<TestOracle, TAddress> | MaybeAccount<TestOracle, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTestOracleDecoder(),
  );
}

export async function fetchTestOracle<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TestOracle, TAddress>> {
  const maybeAccount = await fetchMaybeTestOracle(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTestOracle<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TestOracle, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTestOracle(maybeAccount);
}

export async function fetchAllTestOracle(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TestOracle>[]> {
  const maybeAccounts = await fetchAllMaybeTestOracle(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTestOracle(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TestOracle>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTestOracle(maybeAccount));
}

export function getTestOracleSize(): number {
  return 36;
}
