/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { YVAULTS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SWAP_UNEVEN_VAULTS_DISCRIMINATOR = new Uint8Array([
  143, 212, 101, 95, 105, 209, 184, 1,
]);

export function getSwapUnevenVaultsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SWAP_UNEVEN_VAULTS_DISCRIMINATOR,
  );
}

export type SwapUnevenVaultsInstruction<
  TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS,
  TAccountActionsAuthority extends string | AccountMeta<string> = string,
  TAccountStrategy extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountTokenAVault extends string | AccountMeta<string> = string,
  TAccountTokenBVault extends string | AccountMeta<string> = string,
  TAccountTokenAMint extends string | AccountMeta<string> = string,
  TAccountTokenBMint extends string | AccountMeta<string> = string,
  TAccountBaseVaultAuthority extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountRaydiumPoolConfigOrBaseVaultAuthority extends
    | string
    | AccountMeta<string> = string,
  TAccountPoolTokenVaultA extends string | AccountMeta<string> = string,
  TAccountPoolTokenVaultB extends string | AccountMeta<string> = string,
  TAccountTickArray0 extends string | AccountMeta<string> = string,
  TAccountTickArray1 extends string | AccountMeta<string> = string,
  TAccountTickArray2 extends string | AccountMeta<string> = string,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountPoolProgram extends string | AccountMeta<string> = string,
  TAccountScopePrices extends string | AccountMeta<string> = string,
  TAccountTokenInfos extends string | AccountMeta<string> = string,
  TAccountTickArrayLower extends string | AccountMeta<string> = string,
  TAccountTickArrayUpper extends string | AccountMeta<string> = string,
  TAccountTokenATokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenBTokenProgram extends string | AccountMeta<string> = string,
  TAccountMemoProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountTokenProgram2022 extends string | AccountMeta<string> = string,
  TAccountInstructionSysvarAccount extends string | AccountMeta<string> =
    "Sysvar1nstructions1111111111111111111111111",
  TAccountConsensusAccount extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountActionsAuthority extends string
        ? WritableSignerAccount<TAccountActionsAuthority> &
            AccountSignerMeta<TAccountActionsAuthority>
        : TAccountActionsAuthority,
      TAccountStrategy extends string
        ? WritableAccount<TAccountStrategy>
        : TAccountStrategy,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountTokenAVault extends string
        ? WritableAccount<TAccountTokenAVault>
        : TAccountTokenAVault,
      TAccountTokenBVault extends string
        ? WritableAccount<TAccountTokenBVault>
        : TAccountTokenBVault,
      TAccountTokenAMint extends string
        ? ReadonlyAccount<TAccountTokenAMint>
        : TAccountTokenAMint,
      TAccountTokenBMint extends string
        ? ReadonlyAccount<TAccountTokenBMint>
        : TAccountTokenBMint,
      TAccountBaseVaultAuthority extends string
        ? WritableAccount<TAccountBaseVaultAuthority>
        : TAccountBaseVaultAuthority,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountRaydiumPoolConfigOrBaseVaultAuthority extends string
        ? ReadonlyAccount<TAccountRaydiumPoolConfigOrBaseVaultAuthority>
        : TAccountRaydiumPoolConfigOrBaseVaultAuthority,
      TAccountPoolTokenVaultA extends string
        ? WritableAccount<TAccountPoolTokenVaultA>
        : TAccountPoolTokenVaultA,
      TAccountPoolTokenVaultB extends string
        ? WritableAccount<TAccountPoolTokenVaultB>
        : TAccountPoolTokenVaultB,
      TAccountTickArray0 extends string
        ? WritableAccount<TAccountTickArray0>
        : TAccountTickArray0,
      TAccountTickArray1 extends string
        ? WritableAccount<TAccountTickArray1>
        : TAccountTickArray1,
      TAccountTickArray2 extends string
        ? WritableAccount<TAccountTickArray2>
        : TAccountTickArray2,
      TAccountOracle extends string
        ? WritableAccount<TAccountOracle>
        : TAccountOracle,
      TAccountPoolProgram extends string
        ? ReadonlyAccount<TAccountPoolProgram>
        : TAccountPoolProgram,
      TAccountScopePrices extends string
        ? ReadonlyAccount<TAccountScopePrices>
        : TAccountScopePrices,
      TAccountTokenInfos extends string
        ? ReadonlyAccount<TAccountTokenInfos>
        : TAccountTokenInfos,
      TAccountTickArrayLower extends string
        ? ReadonlyAccount<TAccountTickArrayLower>
        : TAccountTickArrayLower,
      TAccountTickArrayUpper extends string
        ? ReadonlyAccount<TAccountTickArrayUpper>
        : TAccountTickArrayUpper,
      TAccountTokenATokenProgram extends string
        ? ReadonlyAccount<TAccountTokenATokenProgram>
        : TAccountTokenATokenProgram,
      TAccountTokenBTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenBTokenProgram>
        : TAccountTokenBTokenProgram,
      TAccountMemoProgram extends string
        ? ReadonlyAccount<TAccountMemoProgram>
        : TAccountMemoProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountTokenProgram2022 extends string
        ? ReadonlyAccount<TAccountTokenProgram2022>
        : TAccountTokenProgram2022,
      TAccountInstructionSysvarAccount extends string
        ? ReadonlyAccount<TAccountInstructionSysvarAccount>
        : TAccountInstructionSysvarAccount,
      TAccountConsensusAccount extends string
        ? ReadonlyAccount<TAccountConsensusAccount>
        : TAccountConsensusAccount,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SwapUnevenVaultsInstructionData = {
  discriminator: ReadonlyUint8Array;
  targetLimitBps: bigint;
};

export type SwapUnevenVaultsInstructionDataArgs = {
  targetLimitBps: number | bigint;
};

export function getSwapUnevenVaultsInstructionDataEncoder(): FixedSizeEncoder<SwapUnevenVaultsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["targetLimitBps", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SWAP_UNEVEN_VAULTS_DISCRIMINATOR }),
  );
}

export function getSwapUnevenVaultsInstructionDataDecoder(): FixedSizeDecoder<SwapUnevenVaultsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["targetLimitBps", getU64Decoder()],
  ]);
}

export function getSwapUnevenVaultsInstructionDataCodec(): FixedSizeCodec<
  SwapUnevenVaultsInstructionDataArgs,
  SwapUnevenVaultsInstructionData
> {
  return combineCodec(
    getSwapUnevenVaultsInstructionDataEncoder(),
    getSwapUnevenVaultsInstructionDataDecoder(),
  );
}

export type SwapUnevenVaultsInput<
  TAccountActionsAuthority extends string = string,
  TAccountStrategy extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountTokenAVault extends string = string,
  TAccountTokenBVault extends string = string,
  TAccountTokenAMint extends string = string,
  TAccountTokenBMint extends string = string,
  TAccountBaseVaultAuthority extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountRaydiumPoolConfigOrBaseVaultAuthority extends string = string,
  TAccountPoolTokenVaultA extends string = string,
  TAccountPoolTokenVaultB extends string = string,
  TAccountTickArray0 extends string = string,
  TAccountTickArray1 extends string = string,
  TAccountTickArray2 extends string = string,
  TAccountOracle extends string = string,
  TAccountPoolProgram extends string = string,
  TAccountScopePrices extends string = string,
  TAccountTokenInfos extends string = string,
  TAccountTickArrayLower extends string = string,
  TAccountTickArrayUpper extends string = string,
  TAccountTokenATokenProgram extends string = string,
  TAccountTokenBTokenProgram extends string = string,
  TAccountMemoProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountTokenProgram2022 extends string = string,
  TAccountInstructionSysvarAccount extends string = string,
  TAccountConsensusAccount extends string = string,
  TAccountEventAuthority extends string = string,
> = {
  actionsAuthority: TransactionSigner<TAccountActionsAuthority>;
  strategy: Address<TAccountStrategy>;
  globalConfig: Address<TAccountGlobalConfig>;
  tokenAVault: Address<TAccountTokenAVault>;
  tokenBVault: Address<TAccountTokenBVault>;
  tokenAMint: Address<TAccountTokenAMint>;
  tokenBMint: Address<TAccountTokenBMint>;
  baseVaultAuthority: Address<TAccountBaseVaultAuthority>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  raydiumPoolConfigOrBaseVaultAuthority: Address<TAccountRaydiumPoolConfigOrBaseVaultAuthority>;
  poolTokenVaultA: Address<TAccountPoolTokenVaultA>;
  poolTokenVaultB: Address<TAccountPoolTokenVaultB>;
  /** Payer must send this correctly. */
  tickArray0: Address<TAccountTickArray0>;
  /** Payer must send this correctly. */
  tickArray1: Address<TAccountTickArray1>;
  /** Payer must send this correctly. */
  tickArray2: Address<TAccountTickArray2>;
  oracle: Address<TAccountOracle>;
  poolProgram: Address<TAccountPoolProgram>;
  scopePrices: Address<TAccountScopePrices>;
  tokenInfos: Address<TAccountTokenInfos>;
  tickArrayLower: Address<TAccountTickArrayLower>;
  tickArrayUpper: Address<TAccountTickArrayUpper>;
  tokenATokenProgram: Address<TAccountTokenATokenProgram>;
  tokenBTokenProgram: Address<TAccountTokenBTokenProgram>;
  memoProgram: Address<TAccountMemoProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  tokenProgram2022: Address<TAccountTokenProgram2022>;
  instructionSysvarAccount?: Address<TAccountInstructionSysvarAccount>;
  consensusAccount: Address<TAccountConsensusAccount>;
  eventAuthority?: Address<TAccountEventAuthority>;
  targetLimitBps: SwapUnevenVaultsInstructionDataArgs["targetLimitBps"];
};

export function getSwapUnevenVaultsInstruction<
  TAccountActionsAuthority extends string,
  TAccountStrategy extends string,
  TAccountGlobalConfig extends string,
  TAccountTokenAVault extends string,
  TAccountTokenBVault extends string,
  TAccountTokenAMint extends string,
  TAccountTokenBMint extends string,
  TAccountBaseVaultAuthority extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountRaydiumPoolConfigOrBaseVaultAuthority extends string,
  TAccountPoolTokenVaultA extends string,
  TAccountPoolTokenVaultB extends string,
  TAccountTickArray0 extends string,
  TAccountTickArray1 extends string,
  TAccountTickArray2 extends string,
  TAccountOracle extends string,
  TAccountPoolProgram extends string,
  TAccountScopePrices extends string,
  TAccountTokenInfos extends string,
  TAccountTickArrayLower extends string,
  TAccountTickArrayUpper extends string,
  TAccountTokenATokenProgram extends string,
  TAccountTokenBTokenProgram extends string,
  TAccountMemoProgram extends string,
  TAccountTokenProgram extends string,
  TAccountTokenProgram2022 extends string,
  TAccountInstructionSysvarAccount extends string,
  TAccountConsensusAccount extends string,
  TAccountEventAuthority extends string,
  TProgramAddress extends Address = typeof YVAULTS_PROGRAM_ADDRESS,
>(
  input: SwapUnevenVaultsInput<
    TAccountActionsAuthority,
    TAccountStrategy,
    TAccountGlobalConfig,
    TAccountTokenAVault,
    TAccountTokenBVault,
    TAccountTokenAMint,
    TAccountTokenBMint,
    TAccountBaseVaultAuthority,
    TAccountPool,
    TAccountPosition,
    TAccountRaydiumPoolConfigOrBaseVaultAuthority,
    TAccountPoolTokenVaultA,
    TAccountPoolTokenVaultB,
    TAccountTickArray0,
    TAccountTickArray1,
    TAccountTickArray2,
    TAccountOracle,
    TAccountPoolProgram,
    TAccountScopePrices,
    TAccountTokenInfos,
    TAccountTickArrayLower,
    TAccountTickArrayUpper,
    TAccountTokenATokenProgram,
    TAccountTokenBTokenProgram,
    TAccountMemoProgram,
    TAccountTokenProgram,
    TAccountTokenProgram2022,
    TAccountInstructionSysvarAccount,
    TAccountConsensusAccount,
    TAccountEventAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): SwapUnevenVaultsInstruction<
  TProgramAddress,
  TAccountActionsAuthority,
  TAccountStrategy,
  TAccountGlobalConfig,
  TAccountTokenAVault,
  TAccountTokenBVault,
  TAccountTokenAMint,
  TAccountTokenBMint,
  TAccountBaseVaultAuthority,
  TAccountPool,
  TAccountPosition,
  TAccountRaydiumPoolConfigOrBaseVaultAuthority,
  TAccountPoolTokenVaultA,
  TAccountPoolTokenVaultB,
  TAccountTickArray0,
  TAccountTickArray1,
  TAccountTickArray2,
  TAccountOracle,
  TAccountPoolProgram,
  TAccountScopePrices,
  TAccountTokenInfos,
  TAccountTickArrayLower,
  TAccountTickArrayUpper,
  TAccountTokenATokenProgram,
  TAccountTokenBTokenProgram,
  TAccountMemoProgram,
  TAccountTokenProgram,
  TAccountTokenProgram2022,
  TAccountInstructionSysvarAccount,
  TAccountConsensusAccount,
  TAccountEventAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? YVAULTS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    actionsAuthority: {
      value: input.actionsAuthority ?? null,
      isWritable: true,
    },
    strategy: { value: input.strategy ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    tokenAVault: { value: input.tokenAVault ?? null, isWritable: true },
    tokenBVault: { value: input.tokenBVault ?? null, isWritable: true },
    tokenAMint: { value: input.tokenAMint ?? null, isWritable: false },
    tokenBMint: { value: input.tokenBMint ?? null, isWritable: false },
    baseVaultAuthority: {
      value: input.baseVaultAuthority ?? null,
      isWritable: true,
    },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    raydiumPoolConfigOrBaseVaultAuthority: {
      value: input.raydiumPoolConfigOrBaseVaultAuthority ?? null,
      isWritable: false,
    },
    poolTokenVaultA: { value: input.poolTokenVaultA ?? null, isWritable: true },
    poolTokenVaultB: { value: input.poolTokenVaultB ?? null, isWritable: true },
    tickArray0: { value: input.tickArray0 ?? null, isWritable: true },
    tickArray1: { value: input.tickArray1 ?? null, isWritable: true },
    tickArray2: { value: input.tickArray2 ?? null, isWritable: true },
    oracle: { value: input.oracle ?? null, isWritable: true },
    poolProgram: { value: input.poolProgram ?? null, isWritable: false },
    scopePrices: { value: input.scopePrices ?? null, isWritable: false },
    tokenInfos: { value: input.tokenInfos ?? null, isWritable: false },
    tickArrayLower: { value: input.tickArrayLower ?? null, isWritable: false },
    tickArrayUpper: { value: input.tickArrayUpper ?? null, isWritable: false },
    tokenATokenProgram: {
      value: input.tokenATokenProgram ?? null,
      isWritable: false,
    },
    tokenBTokenProgram: {
      value: input.tokenBTokenProgram ?? null,
      isWritable: false,
    },
    memoProgram: { value: input.memoProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    tokenProgram2022: {
      value: input.tokenProgram2022 ?? null,
      isWritable: false,
    },
    instructionSysvarAccount: {
      value: input.instructionSysvarAccount ?? null,
      isWritable: false,
    },
    consensusAccount: {
      value: input.consensusAccount ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.instructionSysvarAccount.value) {
    accounts.instructionSysvarAccount.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.actionsAuthority),
      getAccountMeta(accounts.strategy),
      getAccountMeta(accounts.globalConfig),
      getAccountMeta(accounts.tokenAVault),
      getAccountMeta(accounts.tokenBVault),
      getAccountMeta(accounts.tokenAMint),
      getAccountMeta(accounts.tokenBMint),
      getAccountMeta(accounts.baseVaultAuthority),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.raydiumPoolConfigOrBaseVaultAuthority),
      getAccountMeta(accounts.poolTokenVaultA),
      getAccountMeta(accounts.poolTokenVaultB),
      getAccountMeta(accounts.tickArray0),
      getAccountMeta(accounts.tickArray1),
      getAccountMeta(accounts.tickArray2),
      getAccountMeta(accounts.oracle),
      getAccountMeta(accounts.poolProgram),
      getAccountMeta(accounts.scopePrices),
      getAccountMeta(accounts.tokenInfos),
      getAccountMeta(accounts.tickArrayLower),
      getAccountMeta(accounts.tickArrayUpper),
      getAccountMeta(accounts.tokenATokenProgram),
      getAccountMeta(accounts.tokenBTokenProgram),
      getAccountMeta(accounts.memoProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.tokenProgram2022),
      getAccountMeta(accounts.instructionSysvarAccount),
      getAccountMeta(accounts.consensusAccount),
      getAccountMeta(accounts.eventAuthority),
    ],
    data: getSwapUnevenVaultsInstructionDataEncoder().encode(
      args as SwapUnevenVaultsInstructionDataArgs,
    ),
    programAddress,
  } as SwapUnevenVaultsInstruction<
    TProgramAddress,
    TAccountActionsAuthority,
    TAccountStrategy,
    TAccountGlobalConfig,
    TAccountTokenAVault,
    TAccountTokenBVault,
    TAccountTokenAMint,
    TAccountTokenBMint,
    TAccountBaseVaultAuthority,
    TAccountPool,
    TAccountPosition,
    TAccountRaydiumPoolConfigOrBaseVaultAuthority,
    TAccountPoolTokenVaultA,
    TAccountPoolTokenVaultB,
    TAccountTickArray0,
    TAccountTickArray1,
    TAccountTickArray2,
    TAccountOracle,
    TAccountPoolProgram,
    TAccountScopePrices,
    TAccountTokenInfos,
    TAccountTickArrayLower,
    TAccountTickArrayUpper,
    TAccountTokenATokenProgram,
    TAccountTokenBTokenProgram,
    TAccountMemoProgram,
    TAccountTokenProgram,
    TAccountTokenProgram2022,
    TAccountInstructionSysvarAccount,
    TAccountConsensusAccount,
    TAccountEventAuthority
  >);
}

export type ParsedSwapUnevenVaultsInstruction<
  TProgram extends string = typeof YVAULTS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    actionsAuthority: TAccountMetas[0];
    strategy: TAccountMetas[1];
    globalConfig: TAccountMetas[2];
    tokenAVault: TAccountMetas[3];
    tokenBVault: TAccountMetas[4];
    tokenAMint: TAccountMetas[5];
    tokenBMint: TAccountMetas[6];
    baseVaultAuthority: TAccountMetas[7];
    pool: TAccountMetas[8];
    position: TAccountMetas[9];
    raydiumPoolConfigOrBaseVaultAuthority: TAccountMetas[10];
    poolTokenVaultA: TAccountMetas[11];
    poolTokenVaultB: TAccountMetas[12];
    /** Payer must send this correctly. */
    tickArray0: TAccountMetas[13];
    /** Payer must send this correctly. */
    tickArray1: TAccountMetas[14];
    /** Payer must send this correctly. */
    tickArray2: TAccountMetas[15];
    oracle: TAccountMetas[16];
    poolProgram: TAccountMetas[17];
    scopePrices: TAccountMetas[18];
    tokenInfos: TAccountMetas[19];
    tickArrayLower: TAccountMetas[20];
    tickArrayUpper: TAccountMetas[21];
    tokenATokenProgram: TAccountMetas[22];
    tokenBTokenProgram: TAccountMetas[23];
    memoProgram: TAccountMetas[24];
    tokenProgram: TAccountMetas[25];
    tokenProgram2022: TAccountMetas[26];
    instructionSysvarAccount: TAccountMetas[27];
    consensusAccount: TAccountMetas[28];
    eventAuthority?: TAccountMetas[29] | undefined;
  };
  data: SwapUnevenVaultsInstructionData;
};

export function parseSwapUnevenVaultsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSwapUnevenVaultsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 30) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === YVAULTS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      actionsAuthority: getNextAccount(),
      strategy: getNextAccount(),
      globalConfig: getNextAccount(),
      tokenAVault: getNextAccount(),
      tokenBVault: getNextAccount(),
      tokenAMint: getNextAccount(),
      tokenBMint: getNextAccount(),
      baseVaultAuthority: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      raydiumPoolConfigOrBaseVaultAuthority: getNextAccount(),
      poolTokenVaultA: getNextAccount(),
      poolTokenVaultB: getNextAccount(),
      tickArray0: getNextAccount(),
      tickArray1: getNextAccount(),
      tickArray2: getNextAccount(),
      oracle: getNextAccount(),
      poolProgram: getNextAccount(),
      scopePrices: getNextAccount(),
      tokenInfos: getNextAccount(),
      tickArrayLower: getNextAccount(),
      tickArrayUpper: getNextAccount(),
      tokenATokenProgram: getNextAccount(),
      tokenBTokenProgram: getNextAccount(),
      memoProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      tokenProgram2022: getNextAccount(),
      instructionSysvarAccount: getNextAccount(),
      consensusAccount: getNextAccount(),
      eventAuthority: getNextOptionalAccount(),
    },
    data: getSwapUnevenVaultsInstructionDataDecoder().decode(instruction.data),
  };
}
