/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const CONFIGURATION_DISCRIMINATOR = new Uint8Array([
  192, 79, 172, 30, 21, 173, 25, 43,
]);

export function getConfigurationDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CONFIGURATION_DISCRIMINATOR,
  );
}

export type Configuration = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  oracleMappings: Address;
  oraclePrices: Address;
  tokensMetadata: Address;
  oracleTwaps: Address;
  adminCached: Address;
  emergencyCouncil: Address;
  resumeAuthority: Address;
  padding: Array<bigint>;
};

export type ConfigurationArgs = {
  admin: Address;
  oracleMappings: Address;
  oraclePrices: Address;
  tokensMetadata: Address;
  oracleTwaps: Address;
  adminCached: Address;
  emergencyCouncil: Address;
  resumeAuthority: Address;
  padding: Array<number | bigint>;
};

/** Gets the encoder for {@link ConfigurationArgs} account data. */
export function getConfigurationEncoder(): FixedSizeEncoder<ConfigurationArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
      ["oracleMappings", getAddressEncoder()],
      ["oraclePrices", getAddressEncoder()],
      ["tokensMetadata", getAddressEncoder()],
      ["oracleTwaps", getAddressEncoder()],
      ["adminCached", getAddressEncoder()],
      ["emergencyCouncil", getAddressEncoder()],
      ["resumeAuthority", getAddressEncoder()],
      ["padding", getArrayEncoder(getU64Encoder(), { size: 1247 })],
    ]),
    (value) => ({ ...value, discriminator: CONFIGURATION_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Configuration} account data. */
export function getConfigurationDecoder(): FixedSizeDecoder<Configuration> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
    ["oracleMappings", getAddressDecoder()],
    ["oraclePrices", getAddressDecoder()],
    ["tokensMetadata", getAddressDecoder()],
    ["oracleTwaps", getAddressDecoder()],
    ["adminCached", getAddressDecoder()],
    ["emergencyCouncil", getAddressDecoder()],
    ["resumeAuthority", getAddressDecoder()],
    ["padding", getArrayDecoder(getU64Decoder(), { size: 1247 })],
  ]);
}

/** Gets the codec for {@link Configuration} account data. */
export function getConfigurationCodec(): FixedSizeCodec<
  ConfigurationArgs,
  Configuration
> {
  return combineCodec(getConfigurationEncoder(), getConfigurationDecoder());
}

export function decodeConfiguration<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Configuration, TAddress>;
export function decodeConfiguration<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Configuration, TAddress>;
export function decodeConfiguration<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Configuration, TAddress> | MaybeAccount<Configuration, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getConfigurationDecoder(),
  );
}

export async function fetchConfiguration<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Configuration, TAddress>> {
  const maybeAccount = await fetchMaybeConfiguration(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeConfiguration<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Configuration, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeConfiguration(maybeAccount);
}

export async function fetchAllConfiguration(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Configuration>[]> {
  const maybeAccounts = await fetchAllMaybeConfiguration(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeConfiguration(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Configuration>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeConfiguration(maybeAccount));
}

export function getConfigurationSize(): number {
  return 10240;
}
