/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getTokenMetadataDecoder,
  getTokenMetadataEncoder,
  type TokenMetadata,
  type TokenMetadataArgs,
} from "../types";

export const TOKEN_METADATAS_DISCRIMINATOR = new Uint8Array([
  221, 107, 64, 103, 67, 0, 165, 22,
]);

export function getTokenMetadatasDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TOKEN_METADATAS_DISCRIMINATOR,
  );
}

export type TokenMetadatas = {
  discriminator: ReadonlyUint8Array;
  metadatasArray: Array<TokenMetadata>;
};

export type TokenMetadatasArgs = { metadatasArray: Array<TokenMetadataArgs> };

/** Gets the encoder for {@link TokenMetadatasArgs} account data. */
export function getTokenMetadatasEncoder(): FixedSizeEncoder<TokenMetadatasArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      [
        "metadatasArray",
        getArrayEncoder(getTokenMetadataEncoder(), { size: 512 }),
      ],
    ]),
    (value) => ({ ...value, discriminator: TOKEN_METADATAS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link TokenMetadatas} account data. */
export function getTokenMetadatasDecoder(): FixedSizeDecoder<TokenMetadatas> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    [
      "metadatasArray",
      getArrayDecoder(getTokenMetadataDecoder(), { size: 512 }),
    ],
  ]);
}

/** Gets the codec for {@link TokenMetadatas} account data. */
export function getTokenMetadatasCodec(): FixedSizeCodec<
  TokenMetadatasArgs,
  TokenMetadatas
> {
  return combineCodec(getTokenMetadatasEncoder(), getTokenMetadatasDecoder());
}

export function decodeTokenMetadatas<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<TokenMetadatas, TAddress>;
export function decodeTokenMetadatas<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<TokenMetadatas, TAddress>;
export function decodeTokenMetadatas<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<TokenMetadatas, TAddress> | MaybeAccount<TokenMetadatas, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTokenMetadatasDecoder(),
  );
}

export async function fetchTokenMetadatas<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TokenMetadatas, TAddress>> {
  const maybeAccount = await fetchMaybeTokenMetadatas(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTokenMetadatas<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TokenMetadatas, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTokenMetadatas(maybeAccount);
}

export async function fetchAllTokenMetadatas(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TokenMetadatas>[]> {
  const maybeAccounts = await fetchAllMaybeTokenMetadatas(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTokenMetadatas(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TokenMetadatas>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeTokenMetadatas(maybeAccount),
  );
}

export function getTokenMetadatasSize(): number {
  return 86024;
}
