/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
} from "@solana/kit";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const DECREASE_POSITION_POST_SWAP_DISCRIMINATOR = new Uint8Array([
  75, 246, 208, 7, 203, 66, 106, 91,
]);

export function getDecreasePositionPostSwapDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DECREASE_POSITION_POST_SWAP_DISCRIMINATOR,
  );
}

export type DecreasePositionPostSwapInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountKeeper extends string | AccountMeta<string> = string,
  TAccountPositionRequest extends string | AccountMeta<string> = string,
  TAccountPositionRequestAta extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountKeeper extends string
        ? ReadonlySignerAccount<TAccountKeeper> &
            AccountSignerMeta<TAccountKeeper>
        : TAccountKeeper,
      TAccountPositionRequest extends string
        ? ReadonlyAccount<TAccountPositionRequest>
        : TAccountPositionRequest,
      TAccountPositionRequestAta extends string
        ? ReadonlyAccount<TAccountPositionRequestAta>
        : TAccountPositionRequestAta,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DecreasePositionPostSwapInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type DecreasePositionPostSwapInstructionDataArgs = {};

export function getDecreasePositionPostSwapInstructionDataEncoder(): FixedSizeEncoder<DecreasePositionPostSwapInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: DECREASE_POSITION_POST_SWAP_DISCRIMINATOR,
    }),
  );
}

export function getDecreasePositionPostSwapInstructionDataDecoder(): FixedSizeDecoder<DecreasePositionPostSwapInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDecreasePositionPostSwapInstructionDataCodec(): FixedSizeCodec<
  DecreasePositionPostSwapInstructionDataArgs,
  DecreasePositionPostSwapInstructionData
> {
  return combineCodec(
    getDecreasePositionPostSwapInstructionDataEncoder(),
    getDecreasePositionPostSwapInstructionDataDecoder(),
  );
}

export type DecreasePositionPostSwapInput<
  TAccountKeeper extends string = string,
  TAccountPositionRequest extends string = string,
  TAccountPositionRequestAta extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  keeper: TransactionSigner<TAccountKeeper>;
  positionRequest: Address<TAccountPositionRequest>;
  positionRequestAta: Address<TAccountPositionRequestAta>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
};

export function getDecreasePositionPostSwapInstruction<
  TAccountKeeper extends string,
  TAccountPositionRequest extends string,
  TAccountPositionRequestAta extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: DecreasePositionPostSwapInput<
    TAccountKeeper,
    TAccountPositionRequest,
    TAccountPositionRequestAta,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DecreasePositionPostSwapInstruction<
  TProgramAddress,
  TAccountKeeper,
  TAccountPositionRequest,
  TAccountPositionRequestAta,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    keeper: { value: input.keeper ?? null, isWritable: false },
    positionRequest: {
      value: input.positionRequest ?? null,
      isWritable: false,
    },
    positionRequestAta: {
      value: input.positionRequestAta ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.keeper),
      getAccountMeta(accounts.positionRequest),
      getAccountMeta(accounts.positionRequestAta),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    data: getDecreasePositionPostSwapInstructionDataEncoder().encode({}),
    programAddress,
  } as DecreasePositionPostSwapInstruction<
    TProgramAddress,
    TAccountKeeper,
    TAccountPositionRequest,
    TAccountPositionRequestAta,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedDecreasePositionPostSwapInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    keeper: TAccountMetas[0];
    positionRequest: TAccountMetas[1];
    positionRequestAta: TAccountMetas[2];
    eventAuthority: TAccountMetas[3];
    program: TAccountMetas[4];
  };
  data: DecreasePositionPostSwapInstructionData;
};

export function parseDecreasePositionPostSwapInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDecreasePositionPostSwapInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      keeper: getNextAccount(),
      positionRequest: getNextAccount(),
      positionRequestAta: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getDecreasePositionPostSwapInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
