/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getSideDecoder,
  getSideEncoder,
  type Side,
  type SideArgs,
} from "../types";

export const GET_INCREASE_POSITION_DISCRIMINATOR = new Uint8Array([
  101, 131, 0, 32, 246, 54, 251, 101,
]);

export function getGetIncreasePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GET_INCREASE_POSITION_DISCRIMINATOR,
  );
}

export type GetIncreasePositionInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountCustodyOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountCollateralCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountCustodyOracleAccount>
        : TAccountCustodyOracleAccount,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountCollateralCustodyOracleAccount>
        : TAccountCollateralCustodyOracleAccount,
      ...TRemainingAccounts,
    ]
  >;

export type GetIncreasePositionInstructionData = {
  discriminator: ReadonlyUint8Array;
  collateralTokenDelta: bigint;
  sizeUsdDelta: bigint;
  side: Side;
};

export type GetIncreasePositionInstructionDataArgs = {
  collateralTokenDelta: number | bigint;
  sizeUsdDelta: number | bigint;
  side: SideArgs;
};

export function getGetIncreasePositionInstructionDataEncoder(): FixedSizeEncoder<GetIncreasePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["collateralTokenDelta", getU64Encoder()],
      ["sizeUsdDelta", getU64Encoder()],
      ["side", getSideEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: GET_INCREASE_POSITION_DISCRIMINATOR,
    }),
  );
}

export function getGetIncreasePositionInstructionDataDecoder(): FixedSizeDecoder<GetIncreasePositionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["collateralTokenDelta", getU64Decoder()],
    ["sizeUsdDelta", getU64Decoder()],
    ["side", getSideDecoder()],
  ]);
}

export function getGetIncreasePositionInstructionDataCodec(): FixedSizeCodec<
  GetIncreasePositionInstructionDataArgs,
  GetIncreasePositionInstructionData
> {
  return combineCodec(
    getGetIncreasePositionInstructionDataEncoder(),
    getGetIncreasePositionInstructionDataDecoder(),
  );
}

export type GetIncreasePositionInput<
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralCustodyOracleAccount extends string = string,
> = {
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position?: Address<TAccountPosition>;
  custody: Address<TAccountCustody>;
  custodyOracleAccount: Address<TAccountCustodyOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
  collateralCustodyOracleAccount: Address<TAccountCollateralCustodyOracleAccount>;
  collateralTokenDelta: GetIncreasePositionInstructionDataArgs["collateralTokenDelta"];
  sizeUsdDelta: GetIncreasePositionInstructionDataArgs["sizeUsdDelta"];
  side: GetIncreasePositionInstructionDataArgs["side"];
};

export function getGetIncreasePositionInstruction<
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountCustody extends string,
  TAccountCustodyOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralCustodyOracleAccount extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: GetIncreasePositionInput<
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracleAccount
  >,
  config?: { programAddress?: TProgramAddress },
): GetIncreasePositionInstruction<
  TProgramAddress,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountCustody,
  TAccountCustodyOracleAccount,
  TAccountCollateralCustody,
  TAccountCollateralCustodyOracleAccount
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyOracleAccount: {
      value: input.custodyOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    collateralCustodyOracleAccount: {
      value: input.collateralCustodyOracleAccount ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.perpetuals),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyOracleAccount),
      getAccountMeta(accounts.collateralCustody),
      getAccountMeta(accounts.collateralCustodyOracleAccount),
    ],
    data: getGetIncreasePositionInstructionDataEncoder().encode(
      args as GetIncreasePositionInstructionDataArgs,
    ),
    programAddress,
  } as GetIncreasePositionInstruction<
    TProgramAddress,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyOracleAccount,
    TAccountCollateralCustody,
    TAccountCollateralCustodyOracleAccount
  >);
}

export type ParsedGetIncreasePositionInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    perpetuals: TAccountMetas[0];
    pool: TAccountMetas[1];
    position?: TAccountMetas[2] | undefined;
    custody: TAccountMetas[3];
    custodyOracleAccount: TAccountMetas[4];
    collateralCustody: TAccountMetas[5];
    collateralCustodyOracleAccount: TAccountMetas[6];
  };
  data: GetIncreasePositionInstructionData;
};

export function parseGetIncreasePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGetIncreasePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === PERPETUALS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextOptionalAccount(),
      custody: getNextAccount(),
      custodyOracleAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralCustodyOracleAccount: getNextAccount(),
    },
    data: getGetIncreasePositionInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
