/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const GET_PNL_DISCRIMINATOR = new Uint8Array([
  106, 212, 3, 250, 195, 224, 64, 160,
]);

export function getGetPnlDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(GET_PNL_DISCRIMINATOR);
}

export type GetPnlInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountCustodyOracleAccount extends string | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountCustodyOracleAccount>
        : TAccountCustodyOracleAccount,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      ...TRemainingAccounts,
    ]
  >;

export type GetPnlInstructionData = { discriminator: ReadonlyUint8Array };

export type GetPnlInstructionDataArgs = {};

export function getGetPnlInstructionDataEncoder(): FixedSizeEncoder<GetPnlInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: GET_PNL_DISCRIMINATOR }),
  );
}

export function getGetPnlInstructionDataDecoder(): FixedSizeDecoder<GetPnlInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGetPnlInstructionDataCodec(): FixedSizeCodec<
  GetPnlInstructionDataArgs,
  GetPnlInstructionData
> {
  return combineCodec(
    getGetPnlInstructionDataEncoder(),
    getGetPnlInstructionDataDecoder(),
  );
}

export type GetPnlInput<
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyOracleAccount extends string = string,
  TAccountCollateralCustody extends string = string,
> = {
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  custody: Address<TAccountCustody>;
  custodyOracleAccount: Address<TAccountCustodyOracleAccount>;
  collateralCustody: Address<TAccountCollateralCustody>;
};

export function getGetPnlInstruction<
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountCustody extends string,
  TAccountCustodyOracleAccount extends string,
  TAccountCollateralCustody extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: GetPnlInput<
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyOracleAccount,
    TAccountCollateralCustody
  >,
  config?: { programAddress?: TProgramAddress },
): GetPnlInstruction<
  TProgramAddress,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountCustody,
  TAccountCustodyOracleAccount,
  TAccountCollateralCustody
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyOracleAccount: {
      value: input.custodyOracleAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.perpetuals),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyOracleAccount),
      getAccountMeta(accounts.collateralCustody),
    ],
    data: getGetPnlInstructionDataEncoder().encode({}),
    programAddress,
  } as GetPnlInstruction<
    TProgramAddress,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyOracleAccount,
    TAccountCollateralCustody
  >);
}

export type ParsedGetPnlInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    perpetuals: TAccountMetas[0];
    pool: TAccountMetas[1];
    position: TAccountMetas[2];
    custody: TAccountMetas[3];
    custodyOracleAccount: TAccountMetas[4];
    collateralCustody: TAccountMetas[5];
  };
  data: GetPnlInstructionData;
};

export function parseGetPnlInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGetPnlInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      custody: getNextAccount(),
      custodyOracleAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
    },
    data: getGetPnlInstructionDataDecoder().decode(instruction.data),
  };
}
