/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { PERPETUALS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SWAP_EXACT_OUT_DISCRIMINATOR = new Uint8Array([
  250, 73, 101, 33, 38, 207, 75, 184,
]);

export function getSwapExactOutDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SWAP_EXACT_OUT_DISCRIMINATOR,
  );
}

export type SwapExactOutInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountFundingAccount extends string | AccountMeta<string> = string,
  TAccountReceivingAccount extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountReceivingCustody extends string | AccountMeta<string> = string,
  TAccountReceivingCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TAccountReceivingCustodyTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountDispensingCustody extends string | AccountMeta<string> = string,
  TAccountDispensingCustodyOracleAccount extends string | AccountMeta<string> =
    string,
  TAccountDispensingCustodyTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountFundingAccount extends string
        ? WritableAccount<TAccountFundingAccount>
        : TAccountFundingAccount,
      TAccountReceivingAccount extends string
        ? WritableAccount<TAccountReceivingAccount>
        : TAccountReceivingAccount,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountReceivingCustody extends string
        ? WritableAccount<TAccountReceivingCustody>
        : TAccountReceivingCustody,
      TAccountReceivingCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountReceivingCustodyOracleAccount>
        : TAccountReceivingCustodyOracleAccount,
      TAccountReceivingCustodyTokenAccount extends string
        ? WritableAccount<TAccountReceivingCustodyTokenAccount>
        : TAccountReceivingCustodyTokenAccount,
      TAccountDispensingCustody extends string
        ? WritableAccount<TAccountDispensingCustody>
        : TAccountDispensingCustody,
      TAccountDispensingCustodyOracleAccount extends string
        ? ReadonlyAccount<TAccountDispensingCustodyOracleAccount>
        : TAccountDispensingCustodyOracleAccount,
      TAccountDispensingCustodyTokenAccount extends string
        ? WritableAccount<TAccountDispensingCustodyTokenAccount>
        : TAccountDispensingCustodyTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SwapExactOutInstructionData = {
  discriminator: ReadonlyUint8Array;
  amountOut: bigint;
  maxAmountIn: bigint;
};

export type SwapExactOutInstructionDataArgs = {
  amountOut: number | bigint;
  maxAmountIn: number | bigint;
};

export function getSwapExactOutInstructionDataEncoder(): FixedSizeEncoder<SwapExactOutInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amountOut", getU64Encoder()],
      ["maxAmountIn", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SWAP_EXACT_OUT_DISCRIMINATOR }),
  );
}

export function getSwapExactOutInstructionDataDecoder(): FixedSizeDecoder<SwapExactOutInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amountOut", getU64Decoder()],
    ["maxAmountIn", getU64Decoder()],
  ]);
}

export function getSwapExactOutInstructionDataCodec(): FixedSizeCodec<
  SwapExactOutInstructionDataArgs,
  SwapExactOutInstructionData
> {
  return combineCodec(
    getSwapExactOutInstructionDataEncoder(),
    getSwapExactOutInstructionDataDecoder(),
  );
}

export type SwapExactOutInput<
  TAccountOwner extends string = string,
  TAccountFundingAccount extends string = string,
  TAccountReceivingAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountReceivingCustody extends string = string,
  TAccountReceivingCustodyOracleAccount extends string = string,
  TAccountReceivingCustodyTokenAccount extends string = string,
  TAccountDispensingCustody extends string = string,
  TAccountDispensingCustodyOracleAccount extends string = string,
  TAccountDispensingCustodyTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>;
  fundingAccount: Address<TAccountFundingAccount>;
  receivingAccount: Address<TAccountReceivingAccount>;
  transferAuthority: Address<TAccountTransferAuthority>;
  perpetuals: Address<TAccountPerpetuals>;
  pool: Address<TAccountPool>;
  receivingCustody: Address<TAccountReceivingCustody>;
  receivingCustodyOracleAccount: Address<TAccountReceivingCustodyOracleAccount>;
  receivingCustodyTokenAccount: Address<TAccountReceivingCustodyTokenAccount>;
  dispensingCustody: Address<TAccountDispensingCustody>;
  dispensingCustodyOracleAccount: Address<TAccountDispensingCustodyOracleAccount>;
  dispensingCustodyTokenAccount: Address<TAccountDispensingCustodyTokenAccount>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  amountOut: SwapExactOutInstructionDataArgs["amountOut"];
  maxAmountIn: SwapExactOutInstructionDataArgs["maxAmountIn"];
};

export function getSwapExactOutInstruction<
  TAccountOwner extends string,
  TAccountFundingAccount extends string,
  TAccountReceivingAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountReceivingCustody extends string,
  TAccountReceivingCustodyOracleAccount extends string,
  TAccountReceivingCustodyTokenAccount extends string,
  TAccountDispensingCustody extends string,
  TAccountDispensingCustodyOracleAccount extends string,
  TAccountDispensingCustodyTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: SwapExactOutInput<
    TAccountOwner,
    TAccountFundingAccount,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountReceivingCustodyTokenAccount,
    TAccountDispensingCustody,
    TAccountDispensingCustodyOracleAccount,
    TAccountDispensingCustodyTokenAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SwapExactOutInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountFundingAccount,
  TAccountReceivingAccount,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountReceivingCustody,
  TAccountReceivingCustodyOracleAccount,
  TAccountReceivingCustodyTokenAccount,
  TAccountDispensingCustody,
  TAccountDispensingCustodyOracleAccount,
  TAccountDispensingCustodyTokenAccount,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    fundingAccount: { value: input.fundingAccount ?? null, isWritable: true },
    receivingAccount: {
      value: input.receivingAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    receivingCustody: {
      value: input.receivingCustody ?? null,
      isWritable: true,
    },
    receivingCustodyOracleAccount: {
      value: input.receivingCustodyOracleAccount ?? null,
      isWritable: false,
    },
    receivingCustodyTokenAccount: {
      value: input.receivingCustodyTokenAccount ?? null,
      isWritable: true,
    },
    dispensingCustody: {
      value: input.dispensingCustody ?? null,
      isWritable: true,
    },
    dispensingCustodyOracleAccount: {
      value: input.dispensingCustodyOracleAccount ?? null,
      isWritable: false,
    },
    dispensingCustodyTokenAccount: {
      value: input.dispensingCustodyTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.fundingAccount),
      getAccountMeta(accounts.receivingAccount),
      getAccountMeta(accounts.transferAuthority),
      getAccountMeta(accounts.perpetuals),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.receivingCustody),
      getAccountMeta(accounts.receivingCustodyOracleAccount),
      getAccountMeta(accounts.receivingCustodyTokenAccount),
      getAccountMeta(accounts.dispensingCustody),
      getAccountMeta(accounts.dispensingCustodyOracleAccount),
      getAccountMeta(accounts.dispensingCustodyTokenAccount),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    data: getSwapExactOutInstructionDataEncoder().encode(
      args as SwapExactOutInstructionDataArgs,
    ),
    programAddress,
  } as SwapExactOutInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountFundingAccount,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountReceivingCustody,
    TAccountReceivingCustodyOracleAccount,
    TAccountReceivingCustodyTokenAccount,
    TAccountDispensingCustody,
    TAccountDispensingCustodyOracleAccount,
    TAccountDispensingCustodyTokenAccount,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedSwapExactOutInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    owner: TAccountMetas[0];
    fundingAccount: TAccountMetas[1];
    receivingAccount: TAccountMetas[2];
    transferAuthority: TAccountMetas[3];
    perpetuals: TAccountMetas[4];
    pool: TAccountMetas[5];
    receivingCustody: TAccountMetas[6];
    receivingCustodyOracleAccount: TAccountMetas[7];
    receivingCustodyTokenAccount: TAccountMetas[8];
    dispensingCustody: TAccountMetas[9];
    dispensingCustodyOracleAccount: TAccountMetas[10];
    dispensingCustodyTokenAccount: TAccountMetas[11];
    tokenProgram: TAccountMetas[12];
    eventAuthority: TAccountMetas[13];
    program: TAccountMetas[14];
  };
  data: SwapExactOutInstructionData;
};

export function parseSwapExactOutInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSwapExactOutInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 15) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      fundingAccount: getNextAccount(),
      receivingAccount: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      receivingCustody: getNextAccount(),
      receivingCustodyOracleAccount: getNextAccount(),
      receivingCustodyTokenAccount: getNextAccount(),
      dispensingCustody: getNextAccount(),
      dispensingCustodyOracleAccount: getNextAccount(),
      dispensingCustodyTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getSwapExactOutInstructionDataDecoder().decode(instruction.data),
  };
}
