/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type SwapAmountAndFees = {
  amountIn: bigint;
  amountOut: bigint;
  feeBps: bigint;
  feeToken: bigint;
};

export type SwapAmountAndFeesArgs = {
  amountIn: number | bigint;
  amountOut: number | bigint;
  feeBps: number | bigint;
  feeToken: number | bigint;
};

export function getSwapAmountAndFeesEncoder(): FixedSizeEncoder<SwapAmountAndFeesArgs> {
  return getStructEncoder([
    ["amountIn", getU64Encoder()],
    ["amountOut", getU64Encoder()],
    ["feeBps", getU64Encoder()],
    ["feeToken", getU64Encoder()],
  ]);
}

export function getSwapAmountAndFeesDecoder(): FixedSizeDecoder<SwapAmountAndFees> {
  return getStructDecoder([
    ["amountIn", getU64Decoder()],
    ["amountOut", getU64Decoder()],
    ["feeBps", getU64Decoder()],
    ["feeToken", getU64Decoder()],
  ]);
}

export function getSwapAmountAndFeesCodec(): FixedSizeCodec<
  SwapAmountAndFeesArgs,
  SwapAmountAndFees
> {
  return combineCodec(
    getSwapAmountAndFeesEncoder(),
    getSwapAmountAndFeesDecoder(),
  );
}
