/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getAggregatorRoundDecoder,
  getAggregatorRoundEncoder,
  getHashDecoder,
  getHashEncoder,
  getSwitchboardDecimalDecoder,
  getSwitchboardDecimalEncoder,
  type AggregatorRound,
  type AggregatorRoundArgs,
  type Hash,
  type HashArgs,
  type SwitchboardDecimal,
  type SwitchboardDecimalArgs,
} from ".";

export type AggregatorAccountData = {
  name: ReadonlyUint8Array;
  metadata: ReadonlyUint8Array;
  authorWallet: Address;
  queuePubkey: Address;
  oracleRequestBatchSize: number;
  minOracleResults: number;
  minJobResults: number;
  minUpdateDelaySeconds: number;
  startAfter: bigint;
  varianceThreshold: SwitchboardDecimal;
  forceReportPeriod: bigint;
  expiration: bigint;
  consecutiveFailureCount: bigint;
  nextAllowedUpdateTime: bigint;
  isLocked: boolean;
  schedule: ReadonlyUint8Array;
  latestConfirmedRound: AggregatorRound;
  currentRound: AggregatorRound;
  jobPubkeysData: Array<Address>;
  jobHashes: Array<Hash>;
  jobPubkeysSize: number;
  jobsChecksum: ReadonlyUint8Array;
  authority: Address;
  ebuf: ReadonlyUint8Array;
};

export type AggregatorAccountDataArgs = {
  name: ReadonlyUint8Array;
  metadata: ReadonlyUint8Array;
  authorWallet: Address;
  queuePubkey: Address;
  oracleRequestBatchSize: number;
  minOracleResults: number;
  minJobResults: number;
  minUpdateDelaySeconds: number;
  startAfter: number | bigint;
  varianceThreshold: SwitchboardDecimalArgs;
  forceReportPeriod: number | bigint;
  expiration: number | bigint;
  consecutiveFailureCount: number | bigint;
  nextAllowedUpdateTime: number | bigint;
  isLocked: boolean;
  schedule: ReadonlyUint8Array;
  latestConfirmedRound: AggregatorRoundArgs;
  currentRound: AggregatorRoundArgs;
  jobPubkeysData: Array<Address>;
  jobHashes: Array<HashArgs>;
  jobPubkeysSize: number;
  jobsChecksum: ReadonlyUint8Array;
  authority: Address;
  ebuf: ReadonlyUint8Array;
};

export function getAggregatorAccountDataEncoder(): FixedSizeEncoder<AggregatorAccountDataArgs> {
  return getStructEncoder([
    ["name", fixEncoderSize(getBytesEncoder(), 32)],
    ["metadata", fixEncoderSize(getBytesEncoder(), 128)],
    ["authorWallet", getAddressEncoder()],
    ["queuePubkey", getAddressEncoder()],
    ["oracleRequestBatchSize", getU32Encoder()],
    ["minOracleResults", getU32Encoder()],
    ["minJobResults", getU32Encoder()],
    ["minUpdateDelaySeconds", getU32Encoder()],
    ["startAfter", getI64Encoder()],
    ["varianceThreshold", getSwitchboardDecimalEncoder()],
    ["forceReportPeriod", getI64Encoder()],
    ["expiration", getI64Encoder()],
    ["consecutiveFailureCount", getU64Encoder()],
    ["nextAllowedUpdateTime", getI64Encoder()],
    ["isLocked", getBooleanEncoder()],
    ["schedule", fixEncoderSize(getBytesEncoder(), 32)],
    ["latestConfirmedRound", getAggregatorRoundEncoder()],
    ["currentRound", getAggregatorRoundEncoder()],
    ["jobPubkeysData", getArrayEncoder(getAddressEncoder(), { size: 16 })],
    ["jobHashes", getArrayEncoder(getHashEncoder(), { size: 16 })],
    ["jobPubkeysSize", getU32Encoder()],
    ["jobsChecksum", fixEncoderSize(getBytesEncoder(), 32)],
    ["authority", getAddressEncoder()],
    ["ebuf", fixEncoderSize(getBytesEncoder(), 224)],
  ]);
}

export function getAggregatorAccountDataDecoder(): FixedSizeDecoder<AggregatorAccountData> {
  return getStructDecoder([
    ["name", fixDecoderSize(getBytesDecoder(), 32)],
    ["metadata", fixDecoderSize(getBytesDecoder(), 128)],
    ["authorWallet", getAddressDecoder()],
    ["queuePubkey", getAddressDecoder()],
    ["oracleRequestBatchSize", getU32Decoder()],
    ["minOracleResults", getU32Decoder()],
    ["minJobResults", getU32Decoder()],
    ["minUpdateDelaySeconds", getU32Decoder()],
    ["startAfter", getI64Decoder()],
    ["varianceThreshold", getSwitchboardDecimalDecoder()],
    ["forceReportPeriod", getI64Decoder()],
    ["expiration", getI64Decoder()],
    ["consecutiveFailureCount", getU64Decoder()],
    ["nextAllowedUpdateTime", getI64Decoder()],
    ["isLocked", getBooleanDecoder()],
    ["schedule", fixDecoderSize(getBytesDecoder(), 32)],
    ["latestConfirmedRound", getAggregatorRoundDecoder()],
    ["currentRound", getAggregatorRoundDecoder()],
    ["jobPubkeysData", getArrayDecoder(getAddressDecoder(), { size: 16 })],
    ["jobHashes", getArrayDecoder(getHashDecoder(), { size: 16 })],
    ["jobPubkeysSize", getU32Decoder()],
    ["jobsChecksum", fixDecoderSize(getBytesDecoder(), 32)],
    ["authority", getAddressDecoder()],
    ["ebuf", fixDecoderSize(getBytesDecoder(), 224)],
  ]);
}

export function getAggregatorAccountDataCodec(): FixedSizeCodec<
  AggregatorAccountDataArgs,
  AggregatorAccountData
> {
  return combineCodec(
    getAggregatorAccountDataEncoder(),
    getAggregatorAccountDataDecoder(),
  );
}
