/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from "@solana/kit";

export type CappedFlooredData = {
  sourceEntry: number;
  capEntry: Option<number>;
  floorEntry: Option<number>;
};

export type CappedFlooredDataArgs = {
  sourceEntry: number;
  capEntry: OptionOrNullable<number>;
  floorEntry: OptionOrNullable<number>;
};

export function getCappedFlooredDataEncoder(): Encoder<CappedFlooredDataArgs> {
  return getStructEncoder([
    ["sourceEntry", getU16Encoder()],
    ["capEntry", getOptionEncoder(getU16Encoder())],
    ["floorEntry", getOptionEncoder(getU16Encoder())],
  ]);
}

export function getCappedFlooredDataDecoder(): Decoder<CappedFlooredData> {
  return getStructDecoder([
    ["sourceEntry", getU16Decoder()],
    ["capEntry", getOptionDecoder(getU16Decoder())],
    ["floorEntry", getOptionDecoder(getU16Decoder())],
  ]);
}

export function getCappedFlooredDataCodec(): Codec<
  CappedFlooredDataArgs,
  CappedFlooredData
> {
  return combineCodec(
    getCappedFlooredDataEncoder(),
    getCappedFlooredDataDecoder(),
  );
}
