/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** Price data for standard Chainlink types (v3, v7, v8, v9) */
export type ChainlinkStandardPriceData = { observationsTimestamp: bigint };

export type ChainlinkStandardPriceDataArgs = {
  observationsTimestamp: number | bigint;
};

export function getChainlinkStandardPriceDataEncoder(): FixedSizeEncoder<ChainlinkStandardPriceDataArgs> {
  return getStructEncoder([["observationsTimestamp", getU64Encoder()]]);
}

export function getChainlinkStandardPriceDataDecoder(): FixedSizeDecoder<ChainlinkStandardPriceData> {
  return getStructDecoder([["observationsTimestamp", getU64Decoder()]]);
}

export function getChainlinkStandardPriceDataCodec(): FixedSizeCodec<
  ChainlinkStandardPriceDataArgs,
  ChainlinkStandardPriceData
> {
  return combineCodec(
    getChainlinkStandardPriceDataEncoder(),
    getChainlinkStandardPriceDataDecoder(),
  );
}
