/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum EmaType {
  Ema1h,
}

export type EmaTypeArgs = EmaType;

export function getEmaTypeEncoder(): FixedSizeEncoder<EmaTypeArgs> {
  return getEnumEncoder(EmaType);
}

export function getEmaTypeDecoder(): FixedSizeDecoder<EmaType> {
  return getEnumDecoder(EmaType);
}

export function getEmaTypeCodec(): FixedSizeCodec<EmaTypeArgs, EmaType> {
  return combineCodec(getEmaTypeEncoder(), getEmaTypeDecoder());
}
