/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Fee = { basisPoints: number };

export type FeeArgs = Fee;

export function getFeeEncoder(): FixedSizeEncoder<FeeArgs> {
  return getStructEncoder([["basisPoints", getU32Encoder()]]);
}

export function getFeeDecoder(): FixedSizeDecoder<Fee> {
  return getStructDecoder([["basisPoints", getU32Decoder()]]);
}

export function getFeeCodec(): FixedSizeCodec<FeeArgs, Fee> {
  return combineCodec(getFeeEncoder(), getFeeDecoder());
}
