/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type Hash = { data: ReadonlyUint8Array };

export type HashArgs = Hash;

export function getHashEncoder(): FixedSizeEncoder<HashArgs> {
  return getStructEncoder([["data", fixEncoderSize(getBytesEncoder(), 32)]]);
}

export function getHashDecoder(): FixedSizeDecoder<Hash> {
  return getStructDecoder([["data", fixDecoderSize(getBytesDecoder(), 32)]]);
}

export function getHashCodec(): FixedSizeCodec<HashArgs, Hash> {
  return combineCodec(getHashEncoder(), getHashDecoder());
}
