/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum MarketStatusBehavior {
  AllUpdates,
  Open,
  OpenAndPrePost,
}

export type MarketStatusBehaviorArgs = MarketStatusBehavior;

export function getMarketStatusBehaviorEncoder(): FixedSizeEncoder<MarketStatusBehaviorArgs> {
  return getEnumEncoder(MarketStatusBehavior);
}

export function getMarketStatusBehaviorDecoder(): FixedSizeDecoder<MarketStatusBehavior> {
  return getEnumDecoder(MarketStatusBehavior);
}

export function getMarketStatusBehaviorCodec(): FixedSizeCodec<
  MarketStatusBehaviorArgs,
  MarketStatusBehavior
> {
  return combineCodec(
    getMarketStatusBehaviorEncoder(),
    getMarketStatusBehaviorDecoder(),
  );
}
