/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MintToScopeChain = { mint: Address; scopeChain: Array<number> };

export type MintToScopeChainArgs = MintToScopeChain;

export function getMintToScopeChainEncoder(): FixedSizeEncoder<MintToScopeChainArgs> {
  return getStructEncoder([
    ["mint", getAddressEncoder()],
    ["scopeChain", getArrayEncoder(getU16Encoder(), { size: 4 })],
  ]);
}

export function getMintToScopeChainDecoder(): FixedSizeDecoder<MintToScopeChain> {
  return getStructDecoder([
    ["mint", getAddressDecoder()],
    ["scopeChain", getArrayDecoder(getU16Decoder(), { size: 4 })],
  ]);
}

export function getMintToScopeChainCodec(): FixedSizeCodec<
  MintToScopeChainArgs,
  MintToScopeChain
> {
  return combineCodec(
    getMintToScopeChainEncoder(),
    getMintToScopeChainDecoder(),
  );
}
