/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MostRecentOfData = {
  sourceEntries: Array<number>;
  maxDivergenceBps: number;
  sourcesMaxAgeS: bigint;
};

export type MostRecentOfDataArgs = {
  sourceEntries: Array<number>;
  maxDivergenceBps: number;
  sourcesMaxAgeS: number | bigint;
};

export function getMostRecentOfDataEncoder(): FixedSizeEncoder<MostRecentOfDataArgs> {
  return getStructEncoder([
    ["sourceEntries", getArrayEncoder(getU16Encoder(), { size: 4 })],
    ["maxDivergenceBps", getU16Encoder()],
    ["sourcesMaxAgeS", getU64Encoder()],
  ]);
}

export function getMostRecentOfDataDecoder(): FixedSizeDecoder<MostRecentOfData> {
  return getStructDecoder([
    ["sourceEntries", getArrayDecoder(getU16Decoder(), { size: 4 })],
    ["maxDivergenceBps", getU16Decoder()],
    ["sourcesMaxAgeS", getU64Decoder()],
  ]);
}

export function getMostRecentOfDataCodec(): FixedSizeCodec<
  MostRecentOfDataArgs,
  MostRecentOfData
> {
  return combineCodec(
    getMostRecentOfDataEncoder(),
    getMostRecentOfDataDecoder(),
  );
}
