/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MultiplicationChainData = {
  sourceEntries: Array<number>;
  sourcesMaxAgeS: bigint;
};

export type MultiplicationChainDataArgs = {
  sourceEntries: Array<number>;
  sourcesMaxAgeS: number | bigint;
};

export function getMultiplicationChainDataEncoder(): FixedSizeEncoder<MultiplicationChainDataArgs> {
  return getStructEncoder([
    ["sourceEntries", getArrayEncoder(getU16Encoder(), { size: 6 })],
    ["sourcesMaxAgeS", getU64Encoder()],
  ]);
}

export function getMultiplicationChainDataDecoder(): FixedSizeDecoder<MultiplicationChainData> {
  return getStructDecoder([
    ["sourceEntries", getArrayDecoder(getU16Decoder(), { size: 6 })],
    ["sourcesMaxAgeS", getU64Decoder()],
  ]);
}

export function getMultiplicationChainDataCodec(): FixedSizeCodec<
  MultiplicationChainDataArgs,
  MultiplicationChainData
> {
  return combineCodec(
    getMultiplicationChainDataEncoder(),
    getMultiplicationChainDataDecoder(),
  );
}
