/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum OracleType {
  Pyth,
  DeprecatedPlaceholder1,
  SwitchboardV2,
  DeprecatedPlaceholder2,
  CToken,
  SplStake,
  KToken,
  PythEMA,
  MsolStake,
  KTokenToTokenA,
  KTokenToTokenB,
  JupiterLpFetch,
  ScopeTwap,
  OrcaWhirlpoolAtoB,
  OrcaWhirlpoolBtoA,
  RaydiumAmmV3AtoB,
  RaydiumAmmV3BtoA,
  JupiterLpCompute,
  MeteoraDlmmAtoB,
  MeteoraDlmmBtoA,
  JupiterLpScope,
  PythPull,
  PythPullEMA,
  FixedPrice,
  SwitchboardOnDemand,
  JitoRestaking,
  Chainlink,
  DiscountToMaturity,
  MostRecentOf,
  PythLazer,
  RedStone,
  AdrenaLp,
  Securitize,
  CappedFloored,
  ChainlinkRWA,
  ChainlinkNAV,
  FlashtradeLp,
  ChainlinkX,
  ChainlinkExchangeRate,
  CappedMostRecentOf,
}

export type OracleTypeArgs = OracleType;

export function getOracleTypeEncoder(): FixedSizeEncoder<OracleTypeArgs> {
  return getEnumEncoder(OracleType);
}

export function getOracleTypeDecoder(): FixedSizeDecoder<OracleType> {
  return getEnumDecoder(OracleType);
}

export function getOracleTypeCodec(): FixedSizeCodec<
  OracleTypeArgs,
  OracleType
> {
  return combineCodec(getOracleTypeEncoder(), getOracleTypeDecoder());
}
