/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum PriceUpdateResult {
  Updated,
  SuspendExistingPrice,
}

export type PriceUpdateResultArgs = PriceUpdateResult;

export function getPriceUpdateResultEncoder(): FixedSizeEncoder<PriceUpdateResultArgs> {
  return getEnumEncoder(PriceUpdateResult);
}

export function getPriceUpdateResultDecoder(): FixedSizeDecoder<PriceUpdateResult> {
  return getEnumDecoder(PriceUpdateResult);
}

export function getPriceUpdateResultCodec(): FixedSizeCodec<
  PriceUpdateResultArgs,
  PriceUpdateResult
> {
  return combineCodec(
    getPriceUpdateResultEncoder(),
    getPriceUpdateResultDecoder(),
  );
}
