/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum ReportDataMarketStatus {
  Unknown,
  Closed,
  Open,
}

export type ReportDataMarketStatusArgs = ReportDataMarketStatus;

export function getReportDataMarketStatusEncoder(): FixedSizeEncoder<ReportDataMarketStatusArgs> {
  return getEnumEncoder(ReportDataMarketStatus);
}

export function getReportDataMarketStatusDecoder(): FixedSizeDecoder<ReportDataMarketStatus> {
  return getEnumDecoder(ReportDataMarketStatus);
}

export function getReportDataMarketStatusCodec(): FixedSizeCodec<
  ReportDataMarketStatusArgs,
  ReportDataMarketStatus
> {
  return combineCodec(
    getReportDataMarketStatusEncoder(),
    getReportDataMarketStatusDecoder(),
  );
}
