/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum ReportDataV8MarketStatus {
  Unknown,
  Closed,
  Open,
}

export type ReportDataV8MarketStatusArgs = ReportDataV8MarketStatus;

export function getReportDataV8MarketStatusEncoder(): FixedSizeEncoder<ReportDataV8MarketStatusArgs> {
  return getEnumEncoder(ReportDataV8MarketStatus);
}

export function getReportDataV8MarketStatusDecoder(): FixedSizeDecoder<ReportDataV8MarketStatus> {
  return getEnumDecoder(ReportDataV8MarketStatus);
}

export function getReportDataV8MarketStatusCodec(): FixedSizeCodec<
  ReportDataV8MarketStatusArgs,
  ReportDataV8MarketStatus
> {
  return combineCodec(
    getReportDataV8MarketStatusEncoder(),
    getReportDataV8MarketStatusDecoder(),
  );
}
