/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** Errors that can be raised while creating or manipulating a scope chain */
export enum ScopeChainError {
  PriceChainTooLong,
  PriceChainConversionFailure,
  NoChainForToken,
  InvalidPricesInChain,
  MathOverflow,
  IntegerConversionOverflow,
}

export type ScopeChainErrorArgs = ScopeChainError;

export function getScopeChainErrorEncoder(): FixedSizeEncoder<ScopeChainErrorArgs> {
  return getEnumEncoder(ScopeChainError);
}

export function getScopeChainErrorDecoder(): FixedSizeDecoder<ScopeChainError> {
  return getEnumDecoder(ScopeChainError);
}

export function getScopeChainErrorCodec(): FixedSizeCodec<
  ScopeChainErrorArgs,
  ScopeChainError
> {
  return combineCodec(getScopeChainErrorEncoder(), getScopeChainErrorDecoder());
}
