/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI128Decoder,
  getI128Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type SwitchboardDecimal = { mantissa: bigint; scale: number };

export type SwitchboardDecimalArgs = {
  mantissa: number | bigint;
  scale: number;
};

export function getSwitchboardDecimalEncoder(): FixedSizeEncoder<SwitchboardDecimalArgs> {
  return getStructEncoder([
    ["mantissa", getI128Encoder()],
    ["scale", getU32Encoder()],
  ]);
}

export function getSwitchboardDecimalDecoder(): FixedSizeDecoder<SwitchboardDecimal> {
  return getStructDecoder([
    ["mantissa", getI128Decoder()],
    ["scale", getU32Decoder()],
  ]);
}

export function getSwitchboardDecimalCodec(): FixedSizeCodec<
  SwitchboardDecimalArgs,
  SwitchboardDecimal
> {
  return combineCodec(
    getSwitchboardDecimalEncoder(),
    getSwitchboardDecimalDecoder(),
  );
}
