/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum TokenTypes {
  TokenA,
  TokenB,
}

export type TokenTypesArgs = TokenTypes;

export function getTokenTypesEncoder(): FixedSizeEncoder<TokenTypesArgs> {
  return getEnumEncoder(TokenTypes);
}

export function getTokenTypesDecoder(): FixedSizeDecoder<TokenTypes> {
  return getEnumDecoder(TokenTypes);
}

export function getTokenTypesCodec(): FixedSizeCodec<
  TokenTypesArgs,
  TokenTypes
> {
  return combineCodec(getTokenTypesEncoder(), getTokenTypesDecoder());
}
