/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TwapEnabledBitmask = { bitmask: number };

export type TwapEnabledBitmaskArgs = TwapEnabledBitmask;

export function getTwapEnabledBitmaskEncoder(): FixedSizeEncoder<TwapEnabledBitmaskArgs> {
  return getStructEncoder([["bitmask", getU8Encoder()]]);
}

export function getTwapEnabledBitmaskDecoder(): FixedSizeDecoder<TwapEnabledBitmask> {
  return getStructDecoder([["bitmask", getU8Decoder()]]);
}

export function getTwapEnabledBitmaskCodec(): FixedSizeCodec<
  TwapEnabledBitmaskArgs,
  TwapEnabledBitmask
> {
  return combineCodec(
    getTwapEnabledBitmaskEncoder(),
    getTwapEnabledBitmaskDecoder(),
  );
}
