/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type V3 = { confidenceFactor: number };

export type V3Args = V3;

export function getV3Encoder(): FixedSizeEncoder<V3Args> {
  return getStructEncoder([["confidenceFactor", getU32Encoder()]]);
}

export function getV3Decoder(): FixedSizeDecoder<V3> {
  return getStructDecoder([["confidenceFactor", getU32Decoder()]]);
}

export function getV3Codec(): FixedSizeCodec<V3Args, V3> {
  return combineCodec(getV3Encoder(), getV3Decoder());
}
