/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import {
  getMarketStatusBehaviorDecoder,
  getMarketStatusBehaviorEncoder,
  type MarketStatusBehavior,
  type MarketStatusBehaviorArgs,
} from ".";

export type V8V10 = { marketStatusBehavior: MarketStatusBehavior };

export type V8V10Args = { marketStatusBehavior: MarketStatusBehaviorArgs };

export function getV8V10Encoder(): FixedSizeEncoder<V8V10Args> {
  return getStructEncoder([
    ["marketStatusBehavior", getMarketStatusBehaviorEncoder()],
  ]);
}

export function getV8V10Decoder(): FixedSizeDecoder<V8V10> {
  return getStructDecoder([
    ["marketStatusBehavior", getMarketStatusBehaviorDecoder()],
  ]);
}

export function getV8V10Codec(): FixedSizeCodec<V8V10Args, V8V10> {
  return combineCodec(getV8V10Encoder(), getV8V10Decoder());
}
