/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";
import { getListDecoder, getListEncoder, type List, type ListArgs } from ".";

export type ValidatorSystem = {
  validatorList: List;
  managerAuthority: Address;
  totalValidatorScore: number;
  /** sum of all active lamports staked */
  totalActiveBalance: bigint;
  /** allow & auto-add validator when a user deposits a stake-account of a non-listed validator */
  autoAddValidatorEnabled: number;
};

export type ValidatorSystemArgs = {
  validatorList: ListArgs;
  managerAuthority: Address;
  totalValidatorScore: number;
  /** sum of all active lamports staked */
  totalActiveBalance: number | bigint;
  /** allow & auto-add validator when a user deposits a stake-account of a non-listed validator */
  autoAddValidatorEnabled: number;
};

export function getValidatorSystemEncoder(): FixedSizeEncoder<ValidatorSystemArgs> {
  return getStructEncoder([
    ["validatorList", getListEncoder()],
    ["managerAuthority", getAddressEncoder()],
    ["totalValidatorScore", getU32Encoder()],
    ["totalActiveBalance", getU64Encoder()],
    ["autoAddValidatorEnabled", getU8Encoder()],
  ]);
}

export function getValidatorSystemDecoder(): FixedSizeDecoder<ValidatorSystem> {
  return getStructDecoder([
    ["validatorList", getListDecoder()],
    ["managerAuthority", getAddressDecoder()],
    ["totalValidatorScore", getU32Decoder()],
    ["totalActiveBalance", getU64Decoder()],
    ["autoAddValidatorEnabled", getU8Decoder()],
  ]);
}

export function getValidatorSystemCodec(): FixedSizeCodec<
  ValidatorSystemArgs,
  ValidatorSystem
> {
  return combineCodec(getValidatorSystemEncoder(), getValidatorSystemDecoder());
}
